#include "canvas/Persistency/Common/Wrapper.h"
#include "canvas/Persistency/Common/Assns.h"
#include "lardataobj/AnalysisBase/T0.h"
#include "lardataobj/Simulation/AuxDetSimChannel.h"
#include "sbnobj/Common/CRT/CRTHit.hh"
#include "sbnobj/Common/CRT/CRTTrack.hh"
#include "lardataobj/AnalysisBase/T0.h"
#include "sbnobj/Common/CRT/CRTTzero.hh"
#include "sbnobj/Common/CRT/CRTHit_Legacy.hh"
#include "sbnobj/Common/CRT/CRTTrack_Legacy.hh"
#include "sbnobj/Common/CRT/CRTTzero_Legacy.hh"
#include <vector>
#include <map>
#include <utility>
